### ISSUE TITLE
Separate core models from API; migrate project.json

### ISSUE THREAD

**Issue by johnnyRose** [mikaelsnavy/LircSharpAPI#1]
Nice job on this so far and thanks for creating it. Any objections to separating the core models from the API implementation? I'd be happy to do the work myself.

I'd also like to migrate from the old project.json format and target .NET standard 1.0. Thoughts?

**Comment by mikaelweave** [comment]
I haven't looked at this in like 4 years! Feel free to migrate. I'm a much better C# dev now as well, so let me know if you need anything and I can jump back in. 👍 I can also expand documentation if needed since it's fairly minimal now.

**Comment by johnnyRose** [comment]
Sweet! I went ahead and created a pull request (#2) to merge in these changes. Looking forward to playing around with this.
